spring.application.name=company-service

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Session
server.servlet.session.timeout=24h
server.servlet.session.tracking-modes=cookie
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

# 에러 상세 노출 차단
server.error.include-stacktrace=never
server.error.include-message=never

# 서버 헤더 숨김
server.server-header=
