spring.application.name=company-service

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Session
server.servlet.session.timeout=24h
server.servlet.session.tracking-modes=cookie
